version = 0.1

[default.deploy.parameters]
stack_name = "tan-serverless-dojo"
resolve_s3 = true
s3_prefix = "tan-serverless-dojo"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ProjectName=\"tan-serverless-dojo\" ScheduleState=\"DISABLED\" ScheduleExpression=\"rate(15 minutes)\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
