name: Destroy serverless stack

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      STACK_NAME: tan-serverless-dojo
      AWS_ROLE_TO_ASSUME: arn:aws:iam::923988301700:role/tan-serverless-github-actions-role
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up AWS SAM
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          role-session-name: github-actions-destroy
          aws-region: ${{ env.AWS_REGION }}

      - name: Delete stack
        run: sam delete --stack-name "${STACK_NAME}" --region "${AWS_REGION}" --no-prompts
